### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information)

### ISSUE THREAD

**Issue by pax85** [canalebruno/poketools#1]
Hi, 

Don't know if you're still active here, but just wanted to let you know, that your Home Boxes and SV Boxes App over at https://poketools-blue.vercel.app/homeboxes is no longer loading for the last couple of days.

**Comment by canalebruno** [comment]
Hey, thanks for that! I have redeployed an old version because the latest was causing this, and now it's back. I'll be back to fix that in a couple of weeks. Thanks again!

**Comment by pax85** [comment]
Great news, thanks a lot :)
