### ISSUE TITLE
Paldean Wooper missing in Home Boxes

### ISSUE THREAD

**Issue by pax85** [canalebruno/poketools#2]
Hi,

wanted to let you know that the Paldean Wooper Form seems to be missing. Should be in Box 9 I think.
The SV Boxes correctly show Paldean Wooper.

**Comment by canalebruno** [comment]
Hey,

thank you so much for that! It should be showing now! :) The Paldean Tauros were not showing as well and I fixed them too.

**Comment by pax85** [comment]
ah yes, thought I remembered those missing too, but forgot by the time I chose to create this request :D
